name: Ruby

on:
  - pull_request
  - push

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      FOREMAN_PLUGIN_NAME: foreman_leapp

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: foreman
          POSTGRES_PASSWORD: foreman
          POSTGRES_DB: foreman-test
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install bundler
      run: gem install bundler
    - uses: actions/cache@v1
      with:
        path: ~/vendor/bundle
        key: ${{ runner.os }}-ruby-gems
        restore-keys: |
          ${{ runner.os }}-ruby-gems
    - name: Clone foreman
      run: |
        git clone https://github.com/theforeman/foreman.git ~/foreman --depth 1
        cd ~/foreman
        echo -n "Foreman HEAD SHA1 hash: "
        git show-ref HEAD | awk ' { print $1 } '
        echo "gemspec :path => '${GITHUB_WORKSPACE}'" > bundler.d/${FOREMAN_PLUGIN_NAME}.local.rb
        ln -s settings.yaml.test config/settings.yaml
        cat <<EOF >config/database.yml
        test:
          adapter: postgresql
          port: 5432
          host: localhost
          user: foreman
          password: foreman
          pool: 10
          timeout: 5000
          database: foreman-test
        EOF
    - name: Install dependencies
      run: |
        cd ~/foreman
        bundle config path ~/vendor/bundle
        bundle config set without 'journald development sqlite mysql2 console journald ovirt libvirt ec2 gce openstack rackspace vmware'
        bundle install --jobs=3 --retry=3
    - name: Migrate DB
      run: |
        cd ~/foreman
        bundle exec rake db:migrate RAILS_ENV=test
    - name: Test with rake test:foreman_leapp
      run: |
        cd ~/foreman
        bundle exec rake test:foreman_leapp
